reset_steps:[
  { 
    adb_request: { 
      press_button: { 
        button: HOME  
      }
    }
  }
]

max_episode_steps: 4

log_parsing_config: {
  filters: ["ActivityManager:I"]
  log_regexps: {
    reward_event: {
        event: "^(.*?)Start proc(.*?)com.android.settings.Settings"
        reward: 1
    }
  }
}