reset_steps:[
  { 
    adb_request: { 
      press_button: { 
        button: HOME  
      }
    }
  }
]

max_episode_steps: 6

log_parsing_config: {
  filters: ["SettingsProvider:V"]
  log_regexps: {
    reward_event: {
        event: "^(.*?)vibrate_when_ringing"
        reward: 1
    }
  }
}
