from .check_list_of_posts_I_tagged import check_check_list_of_posts_I_tagged
from .check_my_uploaded_reels_list import check_check_my_uploaded_reels_list
from .go_to_feed_tab import check_go_to_feed_tab  
from .go_to_my_profile import check_go_to_my_profile
from .go_to_search_tab import check_go_to_search_tab
from .go_to_reels_tab import check_go_to_reels_tab

