from .open_calculator import check_open_calculator
from .tap_1 import check_tap_1
from .basic_1 import check_basic_1
from .basic_2 import check_basic_2
from .basic_3 import check_basic_3
from .basic_4 import check_basic_4
from .cos60 import check_cos60
from .cos180 import check_cos180
from .factorial_6 import check_factorial_6
from .sqrt_25 import check_sqrt_25
