OPENAI_API_KEY: ""
GEMINI_API_KEY: ""
HUGGINGFACE_TOKEN: ""
TEMPERATURE: 0.1 # 0.0 for the consistent output of model
TOP_P: 1.0
TOP_K: 42
NUM_RETURN_SEQUENCES: 1
MAX_TOKENS: 256
REPETITION_PENALTY: 1.0
NO_REPEAT_NGRAM_SIZE: 4